### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [dylanmei/iso8601#1]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for iso8601 and versioning would help Debian keep up with development.

**Comment by dylanmei** [comment]
I can set a git tag. What do you expect for versioning it?

**Comment by aviau** [comment]
Tagging and versioning go together :).

See semver: http://semver.org/. Just tag from time to time respecting the SemVer spec.

**Comment by dylanmei** [comment]
Got it. I will tag and version the project.

**Comment by dylanmei** [comment]
v0.1.0: https://github.com/dylanmei/iso8601/tree/v0.1.0

**Comment by aviau** [comment]
Thank you!
